<?php
/**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License version 3.0
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * @author    PrestaShop SA and Contributors <contact@prestashop.com>
 * @copyright Since 2007 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License version 3.0
 */
namespace PrestaShop\Module\DemoProductForm\Entity;

/**
 * Example object model for shipping rules.
 */
final class ShippingRule extends \ObjectModel
{
    /**
     * @var int
     */
    public $id;

    /**
     * @var int
     */
    public $id_product;

    /**
     * @var string
     */
    public $shipping_country;

    /**
     * @var float
     */
    public $shipping_start_rate = 0.0;

    /**
     * @var float
     */
    public $shipping_extra_rate = 0.0;

    /**
     * @var string
     */
    public $date_add;

    /**
     * @var string
     */
    public $date_upd;

    /**
     * @var bool forces the id to be set before saving object (because we don't need autogenerated id for this model)
     */
    public $force_id = true;

    /**
     * The object definition array.
     */
    public static $definition = [
        'table' => 'shipping_rules',
        'primary' => 'id_shipping_rule',
        'fields' => [
            'id_product' => ['type' => self::TYPE_INT, 'validate' => 'isUnsignedInt'],
            'shipping_country' => ['type' => self::TYPE_STRING, 'validate' => 'isString'],
            'shipping_start_rate' => ['type' => self::TYPE_FLOAT, 'validate' => 'isPrice'],
            'shipping_extra_rate' => ['type' => self::TYPE_FLOAT, 'validate' => 'isPrice'],
            'date_add' => ['type' => self::TYPE_DATE, 'validate' => 'isDate'],
            'date_upd' => ['type' => self::TYPE_DATE, 'validate' => 'isDate'],
        ],
    ];
}
